project:
  type: website
  output-dir: docs

website:
  title: "Nick Bell - Tutorial Blog"
  navbar:
    left:
      - href: index.md
        text: Home
      - href: about.qmd
        text: About Me

format:
  html:
    theme: cosmo
    toc: false
